"""SharePoint real data sync and ingestion service."""

from __future__ import annotations

import logging
from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import pandas as pd

from .analytics import (
    BatchClassificationResult,
    FeedbackAnalyticsRepository,
    ingest_managed_workbook,
    read_feedback_workbook,
)
from .analytics.input_reader import sha256_file
from .classification_jobs import ClassificationJobStore
from .pipeline.issue_classifier import MINOR_ORDER, MINOR_TO_MAJOR
from .settings import Settings
from .sharepoint import SharePointClient

logger = logging.getLogger("dms-sharepoint-sync")


@dataclass
class SyncStats:
    """Statistics for SharePoint sync and ingest operation."""

    downloaded_inputs: int = 0
    downloaded_outputs: int = 0
    skipped_inputs: int = 0
    skipped_outputs: int = 0
    ingested_files: int = 0
    classified_files: int = 0
    total_records: int = 0
    errors: list[str] = None  # type: ignore[assignment]

    def __post_init__(self):
        if self.errors is None:
            self.errors = []

    def to_dict(self) -> dict[str, Any]:
        return {
            "downloaded_inputs": self.downloaded_inputs,
            "downloaded_outputs": self.downloaded_outputs,
            "skipped_inputs": self.skipped_inputs,
            "skipped_outputs": self.skipped_outputs,
            "ingested_files": self.ingested_files,
            "classified_files": self.classified_files,
            "total_records": self.total_records,
            "errors": self.errors,
        }


def _get_text(row_vals: list[Any], c_idx: int | None) -> str | None:
    if c_idx is not None and c_idx < len(row_vals):
        v = row_vals[c_idx]
        if pd.notna(v):
            s = str(v).strip()
            if s and s.lower() not in ("nan", "none"):
                return s
    return None


def _get_float(row_vals: list[Any], c_idx: int | None) -> float | None:
    if c_idx is not None and c_idx < len(row_vals):
        v = row_vals[c_idx]
        if pd.notna(v):
            try:
                return float(v)
            except (ValueError, TypeError):
                return None
    return None


def parse_output_results(
    output_path: Path,
    code_to_source_row: dict[str, int],
) -> list[BatchClassificationResult]:
    """Extract classification results and labels from a completed _output.xlsx workbook.

    SharePoint output files generated by the pipeline use a 2-row header:
      - Row 0: Major groups and subheaders for the 21 minor classification labels.
      - Row 1: Column headers (or record data if single header).
      - Row 2+: Data rows with metadata, 'x'/1 flags for labels, and sentiment/model fields.
    """
    try:
        raw_df = pd.read_excel(output_path, header=None, dtype=object)
    except Exception as exc:
        logger.warning("Could not read output workbook %s: %s", output_path.name, exc)
        return []

    if len(raw_df) < 2:
        return []

    # Detect header rows and label columns
    # Check row 0 and row 1 for label occurrences
    row0 = [str(val).strip() if pd.notna(val) else "" for val in raw_df.iloc[0].tolist()]
    row1 = [str(val).strip() if pd.notna(val) else "" for val in raw_df.iloc[1].tolist()]

    label_cols: dict[str, int] = {}
    for col_idx, val in enumerate(row0):
        if val in MINOR_ORDER:
            label_cols[val] = col_idx

    # If row 0 did not have all minor labels, check row 1
    if len(label_cols) < len(MINOR_ORDER):
        for col_idx, val in enumerate(row1):
            if val in MINOR_ORDER and val not in label_cols:
                label_cols[val] = col_idx

    # Identify metadata column indices from row 0 or row 1
    def find_col_idx(*names: str) -> int | None:
        canon_names = {n.strip().lower() for n in names}
        for r in (row0, row1):
            for idx, val in enumerate(r):
                if val.lower() in canon_names:
                    return idx
        return None

    issue_code_idx = find_col_idx("mã vấn đề", "ma van de", "mã vd")
    product_idx = find_col_idx("sản phẩm", "san pham")
    line_idx = find_col_idx("dòng sp", "dong sp")
    model_idx = find_col_idx("model")
    sentiment_idx = find_col_idx("sentiment", "cảm xúc", "cam xuc")
    bm25_idx = find_col_idx("bm25_score", "điểm", "diem")
    content_idx = find_col_idx("nội dung vấn đề", "noi dung van de", "nội dung")

    # Determine data start row: usually row 2 if row 0 had subheaders, or row 1
    # Check if row 1 has STT numeric or issue_code numeric
    data_start_row = 2
    if issue_code_idx is not None and row1[issue_code_idx]:
        val = row1[issue_code_idx]
        if not any(c in val.lower() for c in ("mã", "vấn đề", "code")):
            data_start_row = 1

    results: list[BatchClassificationResult] = []
    for row_idx in range(data_start_row, len(raw_df)):
        row_vals = raw_df.iloc[row_idx].tolist()

        # Extract issue code
        code_str = None
        if issue_code_idx is not None and issue_code_idx < len(row_vals):
            raw_code = row_vals[issue_code_idx]
            if pd.notna(raw_code):
                if isinstance(raw_code, (int, float)):
                    code_str = str(int(raw_code))
                else:
                    code_str = str(raw_code).strip()

        # Resolve to matching input source_row_number
        source_row_num = None
        if code_str and code_str in code_to_source_row:
            source_row_num = code_to_source_row[code_str]

        if source_row_num is None:
            continue

        # Extract active labels
        active_labels: list[str] = []
        for label_name, c_idx in label_cols.items():
            if c_idx < len(row_vals):
                val = row_vals[c_idx]
                if pd.notna(val):
                    val_s = str(val).strip().lower()
                    if val_s in ("x", "1", "true", "yes"):
                        active_labels.append(label_name)

        results.append(
            BatchClassificationResult(
                source_row_number=source_row_num,
                text=_get_text(row_vals, content_idx) or "",
                product=_get_text(row_vals, product_idx),
                product_line=_get_text(row_vals, line_idx),
                model=_get_text(row_vals, model_idx),
                sentiment=_get_text(row_vals, sentiment_idx),
                bm25_score=_get_float(row_vals, bm25_idx),
                labels=active_labels,
                brand=None,
            )
        )

    return results


class SharePointSyncService:
    """Service to download real files from SharePoint and ingest into analytics projection."""

    def __init__(
        self,
        sp_client: SharePointClient,
        settings: Settings,
        analytics_repo: FeedbackAnalyticsRepository,
    ) -> None:
        self.sp_client = sp_client
        self.settings = settings
        self.analytics_repo = analytics_repo

    def download_folder_files(
        self,
        remote_folder: str,
        local_dir: Path,
        stats: SyncStats,
        is_input: bool = True,
    ) -> list[Path]:
        """Download missing or modified .xlsx files from a SharePoint folder."""
        local_dir.mkdir(parents=True, exist_ok=True)
        downloaded_paths: list[Path] = []

        try:
            items = self.sp_client.list_folder_items(remote_folder)
        except Exception as exc:
            msg = f"Cannot list SharePoint folder {remote_folder}: {exc}"
            logger.error(msg)
            stats.errors.append(msg)
            return downloaded_paths

        for item in items:
            name = item.get("name", "")
            if "folder" in item or not name.lower().endswith(".xlsx"):
                continue

            item_id = item.get("id")
            if not item_id:
                continue

            remote_size = int(item.get("size", 0))
            local_path = local_dir / name

            # Skip if file already exists with identical size
            if local_path.is_file() and local_path.stat().st_size == remote_size:
                if is_input:
                    stats.skipped_inputs += 1
                else:
                    stats.skipped_outputs += 1
                downloaded_paths.append(local_path)
                continue

            try:
                logger.info(
                    "Downloading %s (%d bytes) from %s...", name, remote_size, remote_folder
                )
                self.sp_client.download_file(item_id, local_path)
                if is_input:
                    stats.downloaded_inputs += 1
                else:
                    stats.downloaded_outputs += 1
                downloaded_paths.append(local_path)
            except Exception as exc:
                msg = f"Failed to download {name}: {exc}"
                logger.warning(msg)
                stats.errors.append(msg)

        return downloaded_paths

    def ingest_local_files(self, stats: SyncStats) -> None:
        """Ingest all local input files and backfill classification results from output files."""
        input_dir = self.settings.work_dir / "input"
        output_dir = self.settings.work_dir / "output"

        if not input_dir.is_dir():
            return

        input_files = sorted(input_dir.glob("*.xlsx"))
        logger.info("Found %d local input file(s) to inspect for ingestion.", len(input_files))

        ClassificationJobStore(self.analytics_repo.db_path)

        for input_file in input_files:
            try:
                digest = sha256_file(input_file)
                source_file_key = f"sha256:{digest}"
                job_id = f"analytics-ingest-{digest}"

                # 1. Ingest input file snapshot
                ingest_res = ingest_managed_workbook(self.analytics_repo, input_file)
                stats.ingested_files += 1

                # 2. Check if output results need to be applied
                # Find matching output file
                stem = input_file.stem
                candidate_outputs = [
                    output_dir / f"{stem}_output.xlsx",
                    output_dir / f"{stem}.xlsx",
                    output_dir / input_file.name,
                ]
                output_file = next((p for p in candidate_outputs if p.is_file()), None)

                if output_file is not None:
                    # Check if pending records exist in feedback_records for this file
                    with self.analytics_repo._lock, self.analytics_repo._conn() as conn:
                        pending_count = conn.execute(
                            """
                            SELECT COUNT(*) as count FROM feedback_records
                            WHERE source_file_key = ? AND classification_state = 'pending'
                            """,
                            (source_file_key,),
                        ).fetchone()["count"]

                    if pending_count > 0:
                        wb_in = read_feedback_workbook(input_file)
                        code_to_row = {
                            str(r.issue_code): r.source_row_number
                            for r in wb_in.records
                            if r.issue_code
                        }

                        batch_results = parse_output_results(output_file, code_to_row)
                        if batch_results:
                            logger.info(
                                "Applying %d classified records from %s to %s",
                                len(batch_results),
                                output_file.name,
                                input_file.name,
                            )
                            self.analytics_repo.apply_batch_results(
                                job_id=job_id,
                                results=batch_results,
                                minor_to_major=MINOR_TO_MAJOR,
                            )
                            stats.classified_files += 1

                # Update count of total active records
                stats.total_records += ingest_res.persisted_rows

            except Exception as exc:
                msg = f"Error ingesting {input_file.name}: {exc}"
                logger.error(msg)
                stats.errors.append(msg)

    def sync_and_ingest(
        self,
        progress_callback: Callable[[str], None] | None = None,
    ) -> SyncStats:
        """Run full download and ingestion workflow."""
        stats = SyncStats()
        input_dir = self.settings.work_dir / "input"
        output_dir = self.settings.work_dir / "output"

        if progress_callback:
            progress_callback("Đang tải danh sách file từ SharePoint Input/...")

        # 1. Download Input files
        logger.info("Syncing Input folder from SharePoint: %s", self.settings.sp_input_folder)
        self.download_folder_files(self.settings.sp_input_folder, input_dir, stats, is_input=True)

        if progress_callback:
            progress_callback("Đang tải danh sách file từ SharePoint Output/...")

        # 2. Download Output files
        logger.info("Syncing Output folder from SharePoint: %s", self.settings.sp_output_folder)
        self.download_folder_files(
            self.settings.sp_output_folder, output_dir, stats, is_input=False
        )

        if progress_callback:
            progress_callback("Đang phân tích và nạp dữ liệu vào Dashboard...")

        # 3. Ingest files into analytics repository
        self.ingest_local_files(stats)

        logger.info(
            "Sync complete: %d inputs (%d new), %d outputs (%d new), %d ingested, %d classified",
            stats.downloaded_inputs + stats.skipped_inputs,
            stats.downloaded_inputs,
            stats.downloaded_outputs + stats.skipped_outputs,
            stats.downloaded_outputs,
            stats.ingested_files,
            stats.classified_files,
        )

        return stats
